import type { RightNowContext } from "./types";

const DEFAULT_RIGHT_NOW_CONTEXTS: RightNowContext[] = [
  {
    key: "morning",
    label: "Morning",
    emoji: "☀️",
    prefer_genres: ["indie pop", "folk", "acoustic", "singer-songwriter", "pop", "jazz", "soul"],
    avoid_genres: ["metal", "punk", "ambient", "sleep"],
    prompt_hints: "",
  },
  {
    key: "gym",
    label: "Gym / Workout",
    emoji: "💪",
    prefer_genres: ["hip hop", "rap", "metal", "rock", "electronic", "edm", "pop", "punk", "hard rock", "drum and bass"],
    avoid_genres: ["ambient", "classical", "folk", "acoustic", "sleep", "meditation", "jazz"],
    prompt_hints: "",
  },
  {
    key: "driving",
    label: "Driving",
    emoji: "🚗",
    prefer_genres: ["rock", "classic rock", "pop", "hip hop", "country", "alternative", "indie", "electronic"],
    avoid_genres: ["ambient", "classical", "sleep", "meditation"],
    prompt_hints: "",
  },
  {
    key: "deep_work",
    label: "Deep Work",
    emoji: "🧠",
    prefer_genres: ["ambient", "electronic", "post-rock", "classical", "instrumental", "jazz", "lo-fi", "neo-classical"],
    avoid_genres: ["hip hop", "rap", "metal", "pop", "punk", "comedy"],
    prompt_hints: "",
  },
  {
    key: "cooking",
    label: "Cooking",
    emoji: "🍳",
    prefer_genres: ["pop", "soul", "r&b", "jazz", "funk", "bossa nova", "latin", "indie pop"],
    avoid_genres: ["metal", "ambient", "classical", "sleep"],
    prompt_hints: "",
  },
  {
    key: "hosting",
    label: "Hosting / Party",
    emoji: "🎉",
    prefer_genres: ["pop", "indie pop", "soul", "r&b", "funk", "jazz", "latin", "dance"],
    avoid_genres: ["metal", "ambient", "sleep", "meditation"],
    prompt_hints: "",
  },
  {
    key: "walking",
    label: "Walking / Errands",
    emoji: "🚶",
    prefer_genres: ["pop", "indie", "rock", "hip hop", "electronic", "folk", "jazz", "classical"],
    avoid_genres: ["ambient", "sleep", "meditation"],
    prompt_hints: "",
  },
  {
    key: "chill",
    label: "Chill / Background",
    emoji: "🧘",
    prefer_genres: ["lo-fi", "chillhop", "indie", "soul", "r&b", "jazz", "ambient", "neo-soul", "folk"],
    avoid_genres: ["metal", "punk", "edm", "drum and bass"],
    prompt_hints: "",
  },
  {
    key: "winding_down",
    label: "Winding Down",
    emoji: "🌙",
    prefer_genres: ["ambient", "folk", "acoustic", "indie folk", "classical", "singer-songwriter", "jazz", "lo-fi", "neo-soul"],
    avoid_genres: ["metal", "punk", "hip hop", "edm", "drum and bass"],
    prompt_hints: "",
  },
];

export const DEFAULT_CONFIG: Record<string, unknown> = {
  dashboard_modes: ["favorites", "discover", "for_right_now", "surprise"],
  cards_per_mode: 2,
  cooldown_days: 3,
  weight_recent_days: 14,
  weight_medium_days: 30,
  weight_low: 1,
  weight_medium: 3,
  weight_high: 5,
  weight_never_picked_bonus: 2,
  contexts: [
    "driving",
    "gym",
    "deep_work",
    "cooking",
    "winding_down",
    "hosting",
    "morning",
    "walking",
    "chill",
  ],
  randomness_factor: 1.0,
  right_now_contexts: DEFAULT_RIGHT_NOW_CONTEXTS,
};
